#!/bin/sh
set -e

. "$1/setupenv.sh"

mirror="http://http.debian.net/debian/"
release="jessie"
deboot_version="1.0.67"

# Debootstrap uses a different name for the arch.
[ "$arch" = "x86_64" ] && altarch="amd64"

# Fix the shell
echo "/bin/bash --init-file /etc/profile" > "$tmpdir/shell"

# Download and extract debootstrap
filename="debootstrap_${deboot_version}_all.deb"
[ ! -f "$tmpdir/$filename" ] && curl -L "$mirror/pool/main/d/debootstrap/$filename" -o "$tmpdir/$filename"

sh -c "cd '$tmpdir' && ar x '$filename'"
mkdir -p "$tmpdir/debootstrap"
tar xf "$tmpdir/data.tar.gz" -C "$tmpdir/debootstrap"

# Set up the chroot with debootstrap
sudo DEBOOTSTRAP_DIR="$tmpdir/debootstrap/usr/share/debootstrap" "$tmpdir/debootstrap/usr/sbin/debootstrap" --arch "$altarch" "$release" "$destdir" "$mirror"

# Fix the permissions
sudo chown $(id -u).$(id -g) "$destdir"
