set nocompatible
filetype off

" Set plugins
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'a.vim'
Plugin 'Raimondi/delimitMate'
Plugin 'nanotech/jellybeans.vim'

call vundle#end()

" Color scheme
colorscheme jellybeans

" Syntax highlighting
filetype plugin indent on
syntax on

" Whitespace
set tabstop=4
set shiftwidth=4
set expandtab
set autoindent

" Display
set number
set hlsearch
