; Map the < and > keys on ANSI keyboard layouts
^!+0::send("°")
^!+8::send("™")
^!+9::send("±")
^!+p::send("Π")
^!+q::send("Ω")
^!+x::send(">")
^!+z::send("<")
^!0::send("≈")
^!m::send("µ")
^!p::send("π")
