; Map the < and > keys on ANSI keyboard layouts
^!+0::send("°")
^!+8::send("™")
^!+9::send("±")
^!+d::send("Δ")
^!+p::send("Π")
^!+q::send("Ω")
^!+u::send("↑")
^!+x::send(">")
^!+z::send("<")
^!0::send("≈")
^!d::send("δ")
^!i::send("→")
^!m::send("µ")
^!p::send("π")
^!u::send("↓")
^!y::send("←")
