#!/bin/sh

screen_main='eDP' # 'LVDS1'
screen_ext='HDMI1 VGA1 HDMI-A-0 DP-1 DP-2 DisplayPort-1 DisplayPort-2'

input="$(rofi -dmenu -i -p 'Toggle external screen' -no-custom << EOF
Off
Same
External
Left
Right
Above
Below
EOF
)"
input="$(echo "$input" | tr '[:upper:]' '[:lower:]')"

update_feh=false
case "$input" in
    off)
        xrandr --output $screen_main --auto
        for screen in $screen_ext; do
            xrandr --output $screen --$input
        done
        update_feh=true
        ;;

    external)
        xrandr --output $screen_main --off
        for screen in $screen_ext; do
            xrandr --output $screen --auto
        done
        ;;

    same)
        xrandr --output $screen_main --auto
        for screen in $screen_ext; do
            xrandr --output $screen --auto --$input-as $screen_main
        done
        update_feh=true
        ;;

    left|right)
        xrandr --output $screen_main --auto
        for screen in $screen_ext; do
            xrandr --output $screen --auto --$input-of $screen_main
        done
        update_feh=true
        ;;

    above|below)
        xrandr --output $screen_main --auto
        for screen in $screen_ext; do
            xrandr --output $screen --auto --$input $screen_main
        done
        update_feh=true
        ;;
esac

if "$update_feh"; then
    for x in "${XDG_CONFIG_HOME:-$HOME/.config}/fehbg" "$HOME/.fehbg"; do
        if [ -x "$x" ]; then
            "$x"
            break
        fi
    done
fi
