#!/bin/sh

screen_main='eDP' # 'LVDS1'
screen_ext='HDMI1 VGA1 HDMI-A-0 DP-1 DP-2 DisplayPort-0 DisplayPort-1 DisplayPort-2'

input="$(rofi -dmenu -i -p 'Toggle external screen' -no-custom << EOF
Off
Same
External
Left
Right
Above
Below
Set Primary
EOF
)"
input="$(echo "$input" | tr '[:upper:]' '[:lower:]')"

update_feh() {
    for x in "${XDG_CONFIG_HOME:-$HOME/.config}/fehbg" "$HOME/.fehbg"; do
        if [ -x "$x" ]; then
            "$x"
            break
        fi
    done
}

get_current_screen() {
    local cursor="$(xdotool getmouselocation | \
        sed 's/^x:\([^ ]*\) y:\([^ ]*\).*$/\1 \2/')"
    xrandr --current | sed -n 's/^\([^ ]*\) connected \([^ ]*\).*$/\1 \2/p' | \
        tr '+x' ' ' | while IFS= read -r screen
    do
        set -- $screen $cursor
        local s=$1 sw=$2 sh=$3 sx=$4 sy=$5 cx=$6 cy=$7
        local smx=$(( $sx + $sw ))
        local smy=$(( $sy + $sh ))
        if [ $cx -ge $sx -a $cx -lt $smx -a \
             $cy -ge $sy -a $cy -lt $smy ]; then
            echo "$s"
            break
        fi
    done
}

case "$input" in
    off)
        xrandr --output $screen_main --auto
        for screen in $screen_ext; do
            xrandr --output $screen --$input
        done
        update_feh
        ;;

    external)
        for screen in $screen_ext; do
            xrandr --output $screen --auto
        done
        xrandr --output $screen_main --off
        ;;

    same)
        xrandr --output $screen_main --auto
        for screen in $screen_ext; do
            xrandr --output $screen --auto --$input-as $screen_main
        done
        update_feh
        ;;

    left|right)
        xrandr --output $screen_main --auto
        for screen in $screen_ext; do
            xrandr --output $screen --auto --$input-of $screen_main
        done
        update_feh
        ;;

    above|below)
        xrandr --output $screen_main --auto
        for screen in $screen_ext; do
            xrandr --output $screen --auto --$input $screen_main
        done
        update_feh
        ;;

    'set primary')
        screen="$(get_current_screen)"
        test -z $screen || xrandr --output $screen --primary
        ;;
esac
