#!/bin/sh
set -e

lock() {
    $sway && return 0

    # If xss-lock is installed, assume it's enabled and it'll run the right locker
    if command -v xss-lock > /dev/null 2> /dev/null; then
        # Lock and blank the screen...
        xset dpms force off
        return
    fi

    # If xflock4 is available, assume it's a script that locks the screen
    # xfce4-power-manager will use this too
    if command -v xflock4 > /dev/null 2> /dev/null; then
        xflock4; sleep 1; xset s activate
        return
    fi

    # If xautolock is installed, try that...
    if command -v xautolock > /dev/null 2> /dev/null; then
        xautolock -locknow; sleep 1; xset s activate
        return
    fi

    # Or just blank the screen
    xset s activate
}

call_ck() {
    dbus-send --system --print-reply \
        --dest=org.freedesktop.ConsoleKit \
        /org/freedesktop/ConsoleKit/Manager \
        "org.freedesktop.ConsoleKit.Manager.$@" > /dev/null 2> /dev/null
}

call_logind() {
    dbus-send --system --print-reply \
        --dest=org.freedesktop.login1 \
        /org/freedesktop/login1 \
        "org.freedesktop.login1.Manager.$@" > /dev/null 2> /dev/null
}

call() {
    # Try calling xfce4-powermanager or anything like it before trying consolekit2 directly
    # Also added (e)logind support now CK2 is more than deprecated.
    dbus-send --print-reply \
            --dest=org.freedesktop.PowerManagement \
            /org/freedesktop/PowerManagement \
            "org.freedesktop.PowerManagement.$@" > /dev/null 2> /dev/null || {
        case "$1" in
            Suspend) lock; call_ck Suspend boolean:true || call_logind Suspend boolean:true ;;
            Hibernate) lock; call_ck Hibernate boolean:true || call_logind Hibernate boolean:true ;;
            Reboot) call_ck Restart || call_logind Reboot boolean:true ;;
            Shutdown) call_ck Stop || call_logind Poweroff boolean:true ;;
        esac
    }
}

get_seat() {
    # Currently only supports (e)logind
    dbus-send --system --print-reply=literal \
        --dest=org.freedesktop.login1 \
        /org/freedesktop/login1/seat/self \
        org.freedesktop.DBus.Properties.Get \
        string:org.freedesktop.login1.Seat string:Id 2> /dev/null \
        | sed -e 's/^   variant       //' -e 's/^seat/Seat/'
}

call_dm() {
    dbus-send --system --print-reply \
        --dest=org.freedesktop.DisplayManager \
        /org/freedesktop/DisplayManager/"$(get_seat)" \
        "org.freedesktop.DisplayManager.Seat.$@" > /dev/null 2> /dev/null
}

close_programs() {
    # Closes all windows in the session.
    # If programs refuse to close after 1.5 seconds, notify the user, to
    #  avoid losing libreoffice documents or whatnot.
    # NOTE: Doesn't handle notification apps or daemons, only open windows.

    $force && return 0
    $sway && return 0

    # Requires wmctrl to function
    if ! command -v wmctrl > /dev/null 2> /dev/null; then
        return 0
    fi
    wmctrl -l | cut -d ' ' -f 1 | xargs -L1 wmctrl -ic
    local attempts=3
    while [ "$attempts" -gt 0 -a "$(wmctrl -l | wc -l)" -gt 0 ]; do
        sleep 0.5
        local attempts="$(expr "$attempts" - 1)"
    done
    if [ "$(wmctrl -l | wc -l)" -gt 0 ]; then
        i3-nagbar -t error -m 'Some programs refuse to close. Close them manually and try again.' -B "Force $action" "'$program' -f '$action'"
        return 1
    fi
    return 0
}

program="$0"

sway=false
force=false
while [ "$1" ]; do
    case "$1" in
    -s) sway=true; shift; continue ;;
    -f) force=true; shift; continue ;;
    *) break ;;
    esac
done

if [ "$1" ]; then
    action="$1"
else
    action="$(rofi -dmenu -i -p 'Power' -no-custom << EOF
Lock
Logout
Switch User
Suspend
Hibernate
Reboot
Reboot to Windows
Shutdown
EOF
    )"
fi

sleep 0.2
case "$action" in
    Logout) close_programs && i3-msg exit ;;
    Lock) lock ;;  # TODO: Can we tell the power manager to lock?
    Suspend|Hibernate) call "$action" ;;
    Reboot|Shutdown) close_programs && call "$action" ;;
    'Reboot to Windows') close_programs && sudo grub-reboot-windows && call Reboot ;;
    'Switch User') call_dm SwitchToGreeter ;;
esac
