#!/bin/sh
set -e
save_root="${HOME:-/tmp}"  # Directory to use as root for saving screenshots

file="$(mktemp -t Screenshot.XXXXXX)"
trap "rm -f '$file'" EXIT
maim -u -f png "$@" "$file"

input="$(rofi -dmenu -i -p 'Screenshot' << EOF
Save
Save sha
Upload
Clipboard
QRDecode
EOF
)"

func="$(echo "$input " | cut -d ' ' -f 1)"
args="$(echo "$input " | cut -d ' ' -f 2- | xargs)"

case "$func" in
    Save)
        if [ "$args" ]; then
            if [ "$args" = 'sha' ]; then
                sha="$(sha1sum "$file" | cut -d' ' -f1)"
                path="$save_root/$sha.png"
            elif [ -d "$save_root/$args" ]; then
                path="$save_root/$args/Screenshot-$(date +%F-%T).png"
            else
                path="$save_root/$args"
            fi
        else
            path="$save_root/Screenshot-$(date +%F-%T).png"
        fi
        cp "$file" "$path"
        echo "$path" | xclip -selection clipboard -i
        ;;

    Upload)
        error=false
        errorfile="$(mktemp -t Screenshot-curlerr.XXXXXX)"
        #url="$(curl -nsT "$file" 'https://chunk.io/' 2> "$errorfile").png"
        url="$(curl -sT "$file" 'https://transfer.sh/screenshot.png' 2> "$errorfile")" || error=true
        if [ "$error" = false ]; then
            notify-send -a 'Screenshot' 'Upload successful'
            echo "$url" | xclip -selection clipboard -i
        else
            notify-send -a 'Screenshot' 'Failed to upload' "$(cat "$errorfile")"
        fi

        rm -f "$errorfile"
        ;;

    Clipboard)
        xclip -selection clipboard -t image/png -i "$file"
        ;;
    QRDecode)
        zbarimg -1 -q --raw "$file" | xclip -selection clipboard -i
        ;;
esac
