#!/bin/sh
# Requires osu to be running in a firejail called "osu"

set -e

prefix="$HOME/.local/share/firejail/osu"

eval "$(grep -m 1 '^WINE=' "${XDG_CONFIG_HOME:-$HOME/.config}/firejail/setup/osu.sh")"
WINE="${WINE:-wine}"

mkdir -p "$prefix/temp"

for x in "$@"; do
    b="$(basename -- "$x")"
    mv -f -- "$x" "$prefix/temp/$b"
    WINEPREFIX="$prefix" "${XDG_CONFIG_HOME:-$HOME/.config}"/firejail/setup.sh osu shell "$WINE" "C:/users/$USER/Local Settings/Application Data/osu!/osu!.exe" "Z:$prefix/temp/$b"
done
