#!/bin/sh
# Requires osu to be running in a firejail called "osu"

set -e

prefix="$HOME/.firejail/osu"

mkdir -p "$prefix/temp"

for x in "$@"; do
    b="$(basename -- "$x")"
    mv -- "$x" "$prefix/temp/$b"
    WINEPREFIX="$prefix" "${XDG_CONFIG_HOME:-$HOME/.config}"/firejail/setup.sh osu shell wine "C:/users/$USER/Local Settings/Application Data/osu!/osu!.exe" "Z:$prefix/temp/$b"
done
