#!/bin/sh

screen_main='eDP-1' # 'LVDS1'
screen_ext='HDMI-1 DP-1 DP-2' # 'HDMI1 VGA1'

input="$(rofi -dmenu -i -p 'Toggle external screen' -no-custom << EOF
Off
Same
Left
Right
Above
Below
EOF
)"
input="$(echo "$input" | tr '[:upper:]' '[:lower:]')"

case $input in
    off)
        for screen in $screen_ext; do
            xrandr --output $screen --$input
        done
        [ -x ~/.fehbg ] && ~/.fehbg
        ;;

    left|right)
        for screen in $screen_ext; do
            xrandr --output $screen --auto --$input-of $screen_main
        done
        [ -x ~/.fehbg ] && ~/.fehbg
        ;;

    above|below)
        for screen in $screen_ext; do
            xrandr --output $screen --auto --$input $screen_main
        done
        [ -x ~/.fehbg ] && ~/.fehbg
        ;;

    same)
        for screen in $screen_ext; do
            xrandr --output $screen --auto --$input-as $screen_main
        done
        [ -x ~/.fehbg ] && ~/.fehbg
esac
