#!/bin/sh
set -eu
git clean -xdf
if [ "$(git branch -r)" ]; then
    git branch -r --format="%(refname)" | sed -e 's@refs/remotes/@@' | xargs git branch -rd
fi
#git tag -l | xargs git tag -d
git reflog expire --all --expire=now
git gc --aggressive --prune=now
