#!/bin/sh

lock() {
    if command -v xflock4 2> /dev/null; then
        xflock4; sleep 1; xset s activate
    else
        if command -v xautolock 2> /dev/null; then
            xautolock -locknow; sleep 1; xset s activate
        else
            xset s activate
        fi
    fi
}

call_ck() {
    dbus-send --system --print-reply --dest=org.freedesktop.ConsoleKit /org/freedesktop/ConsoleKit/Manager "org.freedesktop.ConsoleKit.Manager.$@" > /dev/null 2> /dev/null
}

call() {
    # Try calling xfce4-powermanager or anything like it before trying consolekit2 directly
    dbus-send --print-reply --dest=org.freedesktop.PowerManagement /org/freedesktop/PowerManagement "org.freedesktop.PowerManagement.$@" > /dev/null 2> /dev/null || {
        echo "PowerManagement failed"
        case "$1" in
            Suspend) lock; call_ck Suspend boolean:true ;;
            Hibernate) lock; call_ck Hibernate boolean:true ;;
            Reboot) call_ck Restart ;;
            Shutdown) call_ck Stop ;;
        esac
    }
}

close_programs() {
    if ! command -v wmctrl 2> /dev/null; then
        return 0
    fi
    wmctrl -l | cut -d ' ' -f 1 | xargs -L1 wmctrl -ic
    local attempts=3
    while [ "$attempts" -gt 0 -a "$(wmctrl -l | wc -l)" -gt 0 ]; do
        sleep 0.5
        local attempts="$(expr "$attempts" - 1)"
    done
    if [ "$(wmctrl -l | wc -l)" -gt 0 ]; then
        i3-nagbar -t error -m "Some programs refuse to close. Close them manually and try again."
        return 1
    fi
    return 0
}

input="$(rofi -dmenu -i -p 'Power' -no-custom << EOF
Lock
Logout
Suspend
Hibernate
Reboot
Shutdown
EOF
)"

sleep 0.5
case "$input" in
    Logout) close_programs && i3-msg exit ;;
    Lock) lock ;;  # TODO: Can we tell the power manager to lock?
    Suspend|Hibernate) call "$input" ;;
    Reboot|Shutdown) close_programs && call "$input" ;;
esac
