#!/bin/sh
set -eu

# https://reproducible-builds.org/docs/archives/

# Future versions of GNU Tar might switch to --format=posix
# https://www.gnu.org/software/tar/manual/html_node/Formats.html#SEC134

# To avoid embedding filename in gzip archive: --no-name
# Xz doesn't embed filenames

mtime=""

while [ "$#" -gt 0 ]; do
    case "$1" in
        -t) mtime="--mtime=@0"; shift ;;
        --) shift; break; ;;
        *) break; ;;
    esac
done

name="$(basename "$1")"
tar --format=gnu \
    --sort=name \
    --owner=0 --group=0 --numeric-owner \
    $mtime \
    -cvf "$name.tar" "$1"
xz -9v "$name.tar"
