#!/bin/sh

opt_local=false
opt_root=false

while [ "$#" -gt 0 ]; do
    case "$1" in
        -l) opt_local=true; shift; ;;
        -lr) opt_local=true; opt_root=true; shift; ;;
        --) shift; break; ;;
        *) break; ;;
    esac
done

ebuild="$1"; shift

sudo='sudo --preserve-env=CC,CXX,CFLAGS,CXXFLAGS,LDFLAGS,USE,MAKEOPTS,NINJAOPTS,FEATURES,PORTAGE_TMPDIR,PORTAGE_USERNAME,PORTAGE_GRPNAME,SANDBOX_ACTIVE,EXTRA_ECONF,EXTRA_EMAKE,MYCMAKEARGS,MYMESONARGS,PYTHON_TARGETS,ALLOW_TEST,GENTOO_MIRRORS'

export MAKEOPTS="${MAKEOPTS:--j$(nproc --ignore=1) -l$(nproc)}"
export FEATURES="test warn-on-large-env $FEATURES"

if ! "$opt_local"; then
    export FEATURES="ccache $FEATURES"
else
    export FEATURES="fakeroot $FEATURES"
    export PORTAGE_TMPDIR="$PWD"
    export PORTAGE_USERNAME="$(id -un)"
    export PORTAGE_GRPNAME="$(id -gn)"
    export PKGDIR="$PORTAGE_TMPDIR/packages"
    mkdir -p "$PORTAGE_TMPDIR"
    if ! "$opt_root"; then
        sudo=
    fi
fi

if [ "$#" -gt 0 ]; then
    exec $sudo ebuild "$ebuild" "$@"
else
    exec $sudo ebuild "$ebuild" manifest clean merge
fi
