#!/bin/sh
set -e

action_get() {
    pkg="$1"
    dir="/etc/portage/patches/$pkg"
    if [ -d "$dir" ]; then
        rsync -rv "$dir/" patches/
    else
        echo "Creating new patchset for $pkg" >&2
        mkdir patches
    fi
    echo "$pkg" > .genpatch
}

action_set() {
    pkg=""
    test -f .genpatch && pkg="$(cat .genpatch)"
    test -n "$1" && pkg="$1"
    if [ -z "$pkg" ]; then
        echo "No package set!" >&2
        exit 1
    fi
    dir="/etc/portage/patches/$pkg/"
    sudo rm -rf "$dir"
    sudo rsync --mkpath -rv patches/ "$dir"
}

case "$1" in
    get) shift; action_get "$@" ;;
    set) shift; action_set "$@" ;;
esac
