#!/bin/sh
set -e

CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/minidlna"
mkdir -p "$CACHE"

cat > "$CACHE/conf" << EOF
user=$USER
media_dir=$1
db_dir=$CACHE
log_dir=$CACHE
EOF
minidlnad -R -d -f "$CACHE/conf"
