#!/bin/sh
# https://stackoverflow.com/questions/29613304/is-it-possible-to-escape-regex-metacharacters-reliably-with-sed
sedescape_regex() {
    printf '%s' "$@" | sed 's/[^^]/[&]/g; s/\^/\\^/g'
}
sedescape_subst() {
    printf '%s' "$@" | sed 's/[&/\]/\\&/g'
}

grep -rwl \
    --include='*.c' --include='*.h' \
    --include='*.asm' --include='*.inc' \
    --include='*.s' --include='*.i' \
    --include='*.ld' \
    --include='*.md' \
    "$1" | xargs sed -i "s/\<$(sedescape_regex "$1")\>/$(sedescape_subst "$2")/g"
