#!/bin/sh
# https://stackoverflow.com/questions/29613304/is-it-possible-to-escape-regex-metacharacters-reliably-with-sed
sedescape_regex() {
    printf '%s' "$@" | sed 's/[^^]/[&]/g; s/\^/\\^/g'
}
sedescape_subst() {
    printf '%s' "$@" | sed 's/[&/\]/\\&/g'
}

regex="$(sedescape_regex "$1")"; shift
subst="$(sedescape_subst "$1")"; shift

grep -rwl \
    --include='*.sh' \
    --include='*.c' --include='*.h' \
    --include='*.asm' --include='*.inc' \
    --include='*.s' --include='*.i' \
    --include='*.ld' \
    --include='*.md' \
    "$regex" "$@" | xargs -t sed -i "s/\<$regex\>/$subst/g"
