#!/bin/sh
tool="${STRIP:-strip}"
find "$@" -type f -print0 | xargs -0 -r file | grep executable | grep ELF | cut -f 1 -d : | xargs -L1 -r -t $tool --strip-all --remove-section=.comment || true
find "$@" -type f -name '*.a' -print0 | xargs -0 -L1 -r -t $tool --strip-debug --remove-section=.comment || true
find "$@" -type f -name '*.so*' -print0 | xargs -0 -L1 -r -t $tool --strip-unneeded --remove-section=.comment || true
