#!/bin/sh
dir="${1:-.}"
tool_host="${2:-strip}"
tool_target="${3:-strip}"
find "$dir" -type f -print0 | xargs -0 -r file | grep 'executable' | grep ELF | cut -f 1 -d : | xargs -L1 -r -t $tool_host --strip-all || true
find "$dir" -type f -name '*.a' | xargs -L1 -r -t $tool_target --strip-debug || true
find "$dir" -type f -name '*.so*' | xargs -L1 -r -t $tool_target --strip-unneeded || true
