#!/bin/sh
set -e

arch="$(uname -m)"
dir="$HOME/.distroot"
bindir="$dir/.bin"

proot_base() {
    # Some terminfos are usually not installed in chroots,
    #   and are mostly compatible with other, installed terminfos.
    if [ "$TERM" = "rxvt-unicode-256color" ]; then
        local TERM="linux"
    fi

    env -i TERM=$TERM "$bindir/proot" -b /dev -b /run -b /sys -b /proc -b /etc/resolv.conf "$@"
}

proot_root() {
    proot_base -0 -w /root -r "$@"
}

proot_user() {
    proot_base -b "$HOME" -b /etc/passwd -b /etc/group -r "$@"
}

chrootcmd() {
    proot_root "$distdir" /usr/bin/env "$@"
}

if [ "$#" -lt 1 ]; then
    echo "Usage: $0 [user] <distribution>"
    exit 1
fi

# Args
if [ "$1" = "user" ]; then
    if [ "$#" -lt 2 ]; then
        echo "Usage: $0 user <disribution>"
        exit 1
    fi
    user=true; shift
fi
dist="$1"; shift

tmpdir="$dir/.tmp/$dist"
distdir="$dir/$dist"
script="$HOME/.scripts/dists/$dist"

if [ ! -f "$bindir/proot" ]; then
    echo "Installing proot"
    mkdir -p "$bindir"
    curl -L "http://portable.proot.me/proot-$arch" -o "$bindir/proot"
    chmod +x "$bindir/proot"
fi

if [ ! -f "$dir/.$dist" ]; then
    # Exit if we don't have a script for this distro
    if [ ! -f "$script" ]; then
        echo "Don't know about a distribution called $dist"
        exit 1
    fi

    # Make sure we can use that dir.
    [ -d "$distdir" ] && rm -rf "$distdir"

    mkdir -p "$distdir"
    mkdir -p "$tmpdir"

    echo "Creating chroot for distribution: $dist"
    . "$script"
    if [ -f "$tmpdir/shell" ]; then
        cp "$tmpdir/shell" "$dir/.$dist"
    else
        touch "$dir/.$dist"
    fi
fi

# Set up the command
if [ "$*" ]; then
    command="$*"
elif [ "$(cat "$dir/.$dist")" ]; then
    command="$(cat "$dir/.$dist")"
fi

if [ -f "$dir/.$dist" ]; then
    if [ "$user" = true ]; then
        proot_user "$distdir" $command
    else
        proot_root "$distdir" $command
    fi
fi
