#!/bin/sh
set -e

command -v jchroot > /dev/null || { echo "This script needs a copy of jchroot"; exit 1; }

arch="$(uname -m)"
dir="$HOME/.distroot"

chroot_base() {
    # Some terminfos are usually not installed in chroots,
    #   and are mostly compatible with other, installed terminfos.
    if [ "$TERM" = "rxvt-unicode-256color" ]; then
        local TERM="linux"
    fi
    dir="$1"; shift

    sudo jchroot "$dir" env -i DISPLAY=$DISPLAY TERM=$TERM $@
}

chroot_root() {
    dir="$1"; shift
    chroot_base "$dir" HOME=/root $@
}

chroot_user() {
    chroot_base $@
}

chrootcmd() {
    chroot_root "$distdir" /usr/bin/env "$@"
}

if [ "$#" -lt 1 ]; then
    echo "Usage: $0 [user] <distribution>"
    exit 1
fi

# Args
if [ "$1" = "user" ]; then
    if [ "$#" -lt 2 ]; then
        echo "Usage: $0 user <disribution>"
        exit 1
    fi
    user=true; shift
fi
dist="$1"; shift

tmpdir="$dir/.tmp/$dist"
distdir="$dir/$dist"
script="$HOME/.scripts/dists/$dist"

if [ ! -f "$dir/.$dist" ]; then
    # Exit if we don't have a script for this distro
    if [ ! -f "$script" ]; then
        echo "Don't know about a distribution called $dist"
        exit 1
    fi

    # Make sure we can use that dir.
    [ -d "$distdir" ] && sudo rm -rf "$distdir"

    mkdir -p "$tmpdir"

    echo "Creating chroot for distribution: $dist"
    . "$script"
    if [ -f "$tmpdir/shell" ]; then
        cp "$tmpdir/shell" "$dir/.$dist"
    else
        touch "$dir/.$dist"
    fi
fi

# Set up the command
if [ "$*" ]; then
    command="$*"
elif [ "$(cat "$dir/.$dist")" ]; then
    command="$(cat "$dir/.$dist")"
fi

if [ -f "$dir/.$dist" ]; then
    if [ "$user" = true ]; then
        chroot_user "$distdir" "$command"
    else
        chroot_root "$distdir" $command
    fi
fi
