#!/bin/sh

ck_call() {
    dbus-send --system --print-reply --dest=org.freedesktop.ConsoleKit /org/freedesktop/ConsoleKit/Manager "org.freedesktop.ConsoleKit.Manager.$@"
}

input="$(rofi -dmenu -i -p 'Power: ' -no-custom << EOF
Lock
Suspend
Hibernate
Reboot
Poweroff
EOF
)"

case "$input" in
    Lock) xautolock -locknow; sleep 1; xset s activate ;;
    Suspend) xautolock -locknow; sleep 1; ck_call Suspend boolean:true ;;
    Hibernate) xautolock -locknow; sleep 1; ck_call Hibernate boolean:true ;;
    Reboot) ck_call Restart ;;
    Poweroff) ck_call Stop ;;
esac
