#!/bin/sh

ck_call() {
    #dbus-send --system --print-reply --dest=org.freedesktop.ConsoleKit /org/freedesktop/ConsoleKit/Manager "org.freedesktop.ConsoleKit.Manager.$@"

    # Requires a power management implementation, such as xfce4-powermanager
    dbus-send --dest=org.freedesktop.PowerManagement /org/freedesktop/PowerManagement "org.freedesktop.PowerManagement.$@"
}

input="$(rofi -dmenu -i -p 'Power: ' -no-custom << EOF
Lock
Suspend
Hibernate
Reboot
Shutdown
EOF
)"

sleep 0.1
case "$input" in
    #Lock) xautolock -locknow; sleep 1; xset s activate ;;
    #Suspend) xautolock -locknow; sleep 1; ck_call Suspend boolean:true ;;
    #Hibernate) xautolock -locknow; sleep 1; ck_call Hibernate boolean:true ;;
    #Reboot) ck_call Restart ;;
    #Poweroff) ck_call Stop ;;

    Lock) xflock4 ;;
    Suspend|Hibernate|Reboot|Shutdown) ck_call "$input" ;;
esac
