#!/bin/sh
save_root="${HOME:-/tmp}"  # Directory to use as root for saving screenshots

file="$(mktemp -t Screenshot.XXXXXX)"
maim -f png $@ "$file"
if [ "$?" != 0 ]; then
    rm -f "$file"
    exit 1
fi

input="$(rofi -dmenu -i -p 'Screenshot: ' << EOF
Save
Save sha
Upload
Clipboard
EOF
)"

func="$(echo "$input " | cut -d ' ' -f 1)"
args="$(echo "$input " | cut -d ' ' -f 2- | xargs)"

case "$func" in
    Save)
        if [ "$args" ]; then
            if [ "$args" = 'sha' ]; then
                sha="$(sha256sum "$file" | cut -d' ' -f1)"
                cp "$file" "$save_root/$sha.png"
            elif [ -d "$save_root/$args" ]; then
                cp "$file" "$save_root/$args/Screenshot-$(date +%F-%T).png"
            else
                cp "$file" "$save_root/$args"
            fi
        else
            cp "$file" "$save_root/Screenshot-$(date +%F-%T).png"
        fi
        ;;

    Upload)
        errorfile="$(mktemp -t Screenshot-curlerr.XXXXXX)"
        url="$(curl -T "$file" 'http://chunk.io' 2> "$errorfile").png"
        if [ "$?" = 0 ]; then
            notify-send -a 'Screenshot' 'Upload successful'
            echo "$url" | xclip -selection clipboard -i
        else
            notify-send -a 'Screenshot' 'Failed to upload' "$(cat "$errorfile")"
        fi

        rm -f "$errorfile"
        ;;

    Clipboard)
        xclip -selection clipboard -t image/png -i "$file"
        ;;
esac

rm -f "$file"
