#!/bin/sh
set -eu
#git clean -xdf
git branch -r --format="%(refname:short)" | xargs -r git branch -rd || true
#git branch --format="%(refname:short)" | xargs git branch -D
#git tag -l | xargs git tag -d
git reflog expire --all --expire=all
git gc --aggressive --prune=now
