" Portable vimrc for different implementations

" IDEAVim
if has("ide")
    set commentary
    set highlightedyank
    set surround
    "set ideajoin  " Insanely slow...
endif

" Settings
set nobackup
set noundofile
set incsearch
set tabstop=4
set shiftwidth=4
set expandtab
filetype plugin indent on
syn on
inoremap ññ <esc>
inoremap ÑÑ <esc>
nnoremap <c-h> <c-w><c-h>
nnoremap <c-j> <c-w><c-j>
nnoremap <c-k> <c-w><c-k>
nnoremap <c-l> <c-w><c-l>
