" Must-have...
set nocompatible

" XDG Base Directory support (https://jorenar.com/blog/vim-xdg)
if empty($MYVIMRC) | let $MYVIMRC = expand('<sfile>:p') | endif

if empty($XDG_CACHE_HOME) | let $XDG_CACHE_HOME = $HOME."/.cache" | endif
if empty($XDG_CONFIG_HOME) | let $XDG_CONFIG_HOME = $HOME."/.config" | endif
if empty($XDG_DATA_HOME) | let $XDG_DATA_HOME = $HOME."/.local/share" | endif
if empty($XDG_STATE_HOME) | let $XDG_STATE_HOME = $HOME."/.local/state" | endif
let $VIM_CACHE=$XDG_CACHE_HOME."/vim"
let $VIM_CONFIG=$XDG_CONFIG_HOME."/vim"
let $VIM_DATA=$XDG_DATA_HOME."/vim"
let $VIM_STATE=$VIM_CACHE  " Keep it in cache for now

" Alternative for windows
if (has("win32") || has("win32unix")) && isdirectory($HOME."/vimfiles")
    let $VIM_DATA=$HOME."/vimfiles"
    let $VIM_CACHE=$VIM_DATA
    let $VIM_CONFIG=$VIM_DATA
    let $VIM_STATE=$VIM_DATA
endif

if !has('nvim')
    set runtimepath^=$VIM_CONFIG
    set runtimepath+=$VIM_DATA
    set runtimepath+=$VIM_CONFIG/after

    set packpath^=$VIM_DATA,$VIM_CONFIG
    set packpath+=$VIM_CONFIG/after,$VIM_DATA/after

    set backupdir=$VIM_STATE/backup | call mkdir(&backupdir, 'p', 0700)
    set directory=$VIM_STATE/swap | call mkdir(&directory, 'p', 0700)
    set viewdir=$VIM_STATE/view | call mkdir(&viewdir, 'p', 0700)
    set undodir=$VIM_STATE/undo | call mkdir(&undodir, 'p', 0700)
    set viminfofile=$VIM_STATE/viminfo
endif

let g:netrw_home=$VIM_DATA
let g:plug_home=$VIM_DATA."/plugged"
call mkdir($VIM_DATA."/spell", 'p', 0700)
call mkdir($VIM_STATE, 'p', 0700)

" Check for plug
let data_dir = has('nvim') ? stdpath('data') . '/site' : $VIM_DATA
let has_plug = !empty(glob(data_dir . '/autoload/plug.vim'))

" Convenience setup function
if !has_plug && !exists('*Vimrc_setupplug')
    function! Vimrc_setupplug()
        let data_dir = has('nvim') ? stdpath('data') . '/site' : $VIM_DATA
        silent execute '!curl -fLo "'.data_dir.'/autoload/plug.vim" --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
        source $MYVIMRC
        PlugInstall --sync
        source $MYVIMRC
    endfunction
    command SetupPlug call Vimrc_setupplug()
endif

" Set plugins
if has_plug
    call plug#begin()

    " Themes
    Plug 'junegunn/seoul256.vim'
    "Plug 'sainnhe/everforest'

    " Faaancy
    Plug 'airblade/vim-gitgutter'  " Show git diffs on the side
    Plug 'machakann/vim-highlightedyank'  " Highlight what you've copied

    " File types
    Plug 'lepture/vim-jinja'
    Plug 'lervag/vimtex', { 'tag': 'v2.18' }  " Last Vim 9.1 release
    Plug 'ARM9/arm-syntax-vim'
    Plug 'jakykong/vim-zim', { 'for': 'zim' }
    Plug 'zah/nim.vim'

    " Project management
    Plug 'editorconfig/editorconfig-vim'  " Support editorconfig spec
    Plug 'embear/vim-localvimrc'  " Support per-project vimrc files
    Plug 'ludovicchabant/vim-gutentags'  " Auto-update tags file
    Plug 'ctrlpvim/ctrlp.vim'  " Fuzzy finding file and tag browser

    " Editing
    Plug 'scrooloose/nerdcommenter'  " Comment easily (easily my most-used plugin)
    Plug 'LunarWatcher/auto-pairs'  " Auto-close quotes, parens, etc...
    Plug 'tpope/vim-endwise'  " Auto-end if statements in several languages
    Plug 'tpope/vim-surround'  " Bindings too hard to remember and use tbhon
    Plug 'tpope/vim-repeat'  " Allow pluggins to hook into '.' repeat
    Plug 'junegunn/vim-easy-align'  " Alignment commands bound to 'ga'
    Plug 'junegunn/goyo.vim'  " Distraction-free editing
    Plug 'michaeljsmith/vim-indent-object'  " Select indentation levels
    "Plug 'dpelle/vim-LanguageTool'  " Grammar correction
    Plug 'https://codeberg.org/lifepillar/vim-mucomplete'

    call plug#end()
endif

" Builtin vim plugins (current list for vim 8.2 or newer)
packadd! matchit
packadd! justify
"packadd! editexisting  " Interesting, but won't enable for now

" Theming (seoul256)
let g:seoul256_background=233
"set termguicolors
if has_plug | silent! colorscheme seoul256 | endif
if has("win32") | set guifont=DejaVu_Sans_Mono:h10:cANSI:qDRAFT | endif

" Theming (everforest)
"set background=dark
"let g:everforest_background="hard"
"let g:everforest_better_performance=1
"let g:everforest_disable_italic_comment=1
"let g:everforest_ui_contrast="high"
"let g:everforest_colors_override = {
"    \ "bg0": ["#262626", "235"],
"    \ "bg1": ["#303030", "236"]}
"set termguicolors
"colorscheme everforest

" Syntax highlighting
filetype plugin indent on
syntax on

" Whitespace
set tabstop=4
set shiftwidth=4
set expandtab
set smarttab
set autoindent
set shiftround
set listchars=tab:>-,space:·
set cinoptions+=:0  " Don't indent case in switch

" Display
set number
set hlsearch
set incsearch
set statusline=%f
if has_plug | set colorcolumn=80 | endif  " Looks awful without theme

highlight ExtraWhitespace ctermbg=234
"au BufWinEnter * match ExtraWhitespace /\s\+$/

" Behavior
set modeline
set omnifunc=syntaxcomplete#Complete
set completeopt-=preview
set completeopt+=menuone
set completeopt+=noinsert
set mouse=a
set ttyfast
set clipboard=unnamed
set clipboard+=unnamedplus
set backup
set undofile
set fileencodings=ucs-bom,utf-8,sjis,default  " Try SHIFT-JIS
if has("patch-8.1.0360") | set diffopt+=internal,algorithm:patience | endif  " Use slower but better diff algorithm
let &backupdir=&backupdir."//"  " Make backups with their full path
let &directory=&directory."//"  " Make swapfiles with their full path

" Keybinds
let mapleader="-"
let maplocalleader="_"
nnoremap <F1> :make<cr>
nnoremap <F12> :syntax sync fromstart<cr>
nnoremap <C-d> :set invlist<cr>
nnoremap <C-n> :NERDTreeToggle<cr>
nnoremap <leader>. :CtrlPTag<cr>
nnoremap <leader>n :noh<cr>
nnoremap <leader>ve :split ~/.config/vim/vimrc<cr>
nnoremap <leader>vs :source ~/.config/vim/vimrc<cr>
nnoremap <leader>tb :call Tabs(8)<cr>
nnoremap <leader>ts :call Tabs(4)<cr>
nnoremap <leader>tn :call Tabs(0)<cr>
nnoremap <leader>l :call Line()<cr>

" Behavioral keybinds
"" Escape alternative
inoremap ÑÑ <esc>
inoremap ññ <esc>
"" Auto-indent on paste
"nnoremap p p=`]
"nnoremap P P=`]
"nnoremap <c-p> p
"nnoremap <c-P> P
"" Easier split movement
noremap <C-h> <C-w><C-h>
noremap <C-j> <C-w><C-j>
noremap <C-k> <C-w><C-k>
noremap <C-l> <C-w><C-l>

" vim -b : edit binary using xxd-format!
augroup Binary
    au!
    au BufReadPre *.bin setlocal binary
    au BufReadPost * if &binary | %!xxd
    au BufReadPost * set ft=xxd | endif
    au BufWritePre * if &binary | %!xxd -r
    au BufWritePre * endif
    au BufWritePost * if &binary | %!xxd
    au BufWritePost * set nomod | endif
augroup END

augroup vimrcEx
    au!
    au FileType text setlocal textwidth=78
    au FileType markdown setlocal linebreak
augroup END

" auto-pairs
let g:AutoPairsMapBS=1
let g:AutoPairsMultilineBackspace=1
let g:AutoPairsCenterLine=0

" CtrlP
let g:ctrlp_map="<C-u>"
let g:ctrlp_prompt_mappings={
  \ 'AcceptSelection("h")': ["<C-i>"],
  \ 'AcceptSelection("v")': ["<C-x>"],
  \ }
let g:ctrlp_lazy_update=1

" EasyAlign
nmap ga <Plug>(EasyAlign)
xmap ga <Plug>(EasyAlign)

" NERDTree
let g:NERDTreeQuitOnOpen=1

" NERDCommenter
let g:NERDAltDelims_c=1
let g:NERDCustomDelimiters={"rgbds": {"left": ";", "right": ""}}

" Localvimrc
let g:localvimrc_sandbox=0
let g:localvimrc_count=1
let g:localvimrc_persistent=1
let g:localvimrc_persistence_file=$XDG_DATA_HOME."/vim/localvimrc_persistent"

" Ctags
set tags=.tags
let g:gutentags_ctags_tagfile=".tags"
let g:gutentags_project_root=[".tags"]
let g:ctrlp_root_markers=[".tags"]
let g:TagHighlightSettings={"TagFileName": ".tags"}

" Gutentags
if has_plug | set statusline+=\ %{gutentags#statusline()} | endif
let g:gutentags_add_default_project_roots=0

" vimtex
let g:tex_flavor="latex"
let g:vimtex_view_general_viewer="okular"
let g:vimtex_view_general_options="--unique file:@pdf\#src:@line@tex"
"let g:vimtex_view_general_viewer="xpdf"

" vim-highlightedyank
let g:highlightedyank_highlight_duration=400
highlight HighlightedyankRegion cterm=reverse gui=reverse

" vim-LanguageTool
let g:languagetool_jar=$XDG_DATA_HOME."/vim/languagetool/languagetool-commandline.jar"

" vim-zim
let g:zim_notebooks_dir="/."  " Fix ftdetect when plugin is unloaded

" MUcomplete
let g:mucomplete#enable_auto_at_startup=1

" Utility functions
function Tabs(stop)
    " Quickly switch to and from tabs
    if a:stop != 0
        let &tabstop=a:stop
        let &shiftwidth=a:stop
        set noexpandtab
        set nosmarttab
    else
        set tabstop=4
        set shiftwidth=4
        set expandtab
        set smarttab
    endif
endfunction
function Line()
    " Make non-wrapped text documents readable
    set textwidth=0 linebreak wrap
endfunction
