#!/bin/sh

exec_picom() { exec picom; }
exec_polybar() { exec polybar example; }
exec_volumeicon() { exec volumeicon; }

wait_pipewire() {
    for x in $(seq 400); do  # 4s timeout
        test -n "$XDG_RUNTIME_DIR" -a -S "$XDG_RUNTIME_DIR/pipewire-0" && return 0
        test -S /run/pipewire/pipewire-0 && return 0
        sleep .01
    done
    return 1
}

wait_alsa() {
    for x in $(seq 400); do  # 4s timeout
        amixer get Master 2>&1 > /dev/null && return 0
        sleep .01
    done
    return 1
}

wait_polybar() {
    for x in $(seq 400); do  # 4s timeout
        xprop -name 'Polybar tray window' 2>&1 > /dev/null && return 0
        sleep .01
    done
    return 1
}

all_rein() {
    ( killall -q picom && sleep 1; exec_picom & ) &
    ( killall -q polybar && sleep 2; exec_polybar & ) &
    ( killall -q volumeicon && sleep 2; exec_volumeicon & ) &
}

all_init() {
    xss-lock --ignore-sleep -l -- ~/.config/i3/locker -n &
    xfconf-query -c xfce4-session -p /general/LockCommand -n -t string -s "$HOME/.config/scripts/i3-power Lock_noblank"
    xset s off  # Managed by xfce4-power-manager
    xset r rate 300 50

    # Start pipewire in a sane order
    pipewire &
    pipewire-pulse &
    if wait_pipewire; then
        wireplumber &
    fi &

    # Desktop-related daemons
    "${XDG_CONFIG_HOME:-$HOME/.config}/fehbg" || \
        feh --bg-scale "${XDG_CONFIG_HOME:-$HOME/.config}/wallpaper.jpg"
    exec_picom &
    #snixembed --fork  # crashing and hanging piece of shit
    fcitx
    /usr/lib64/libexec/polkit-kde-authentication-agent-1 &
    urxvtd &
    redshift &
    xfce4-power-manager &
    udiskie &

    # Some things depend on audio/alsa
    if wait_alsa; then
        exec_polybar &
        exec_volumeicon &
    fi &

    # Some things depend on the presence of a tray
    if wait_polybar; then
        wpa_gui -t &
        kdeconnect-indicator &
    fi &

    # Misc applications
    #blueman-applet &
    telegram-desktop -startintray &
}

case "$1" in
    init) all_init ;;
    rein) all_rein ;;
esac
