#!/bin/sh

polybar_exec() { exec polybar example; }
volumeicon_exec() { exec volumeicon; }

all_rein() {
    ( killall -q polybar && sleep 2; polybar_exec & ) &
    ( killall -q volumeicon && sleep 2; volumeicon_exec & ) &
}

all_init() {
    xss-lock --ignore-sleep -l -- ~/.config/i3/locker -n &
    xfconf-query -c xfce4-session -p /general/LockCommand -n -t string -s "$HOME/.config/scripts/power Lock_noblank"
    xset s off  # Managed by xfce4-power-manager
    xset r rate 300 50

    # Start pipewire in a sane order
    pipewire &
    pipewire-pulse &
    ( sleep .5; ( exec wireplumber ) & sleep .5 ) &
    pipewire_sleep="$!"

    # Desktop-related daemons
    "${XDG_CONFIG_HOME:-$HOME/.config}/fehbg"
    #snixembed --fork  # crashing and hanging piece of shit
    fcitx
    picom &
    /usr/lib64/libexec/polkit-kde-authentication-agent-1 &
    urxvtd &
    redshift &
    xfce4-power-manager &
    udiskie &

    # Some things depend on pipewire
    wait "$pipewire_sleep"
    polybar_exec &
    volumeicon_exec &

    # Other things depend on the presence of a tray
    wpa_gui -t &

    # Misc applications
    #blueman-applet &
    telegram-desktop -startintray &
}

case "$1" in
    init) all_init ;;
    rein) all_rein ;;
esac
