#!/bin/sh

# i3lock-color
T='#ccccccff'  # text
i3lock \
--time-color=$T \
--date-color=$T \
\
--blur 5 \
--clock \
--indicator \
"$@" && exit

# Regular i3lock
i3lock \
-i "$HOME/.config/wallpaper.jpg" \
"$@"
